### ISSUE TITLE
`CXXABI_1.3.9' not found

### ISSUE THREAD

**Issue by puncan** [momargoh/MCycle#1]
When attempting to import mcycle in Python, I receive an Import Error which has this at the end:

/anaconda3/bin/../lib/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/usrname/anaconda3/lib/python3.6/site-packages/scipy/sparse/_sparsetools.cpython-36m-x86_64-linux-gnu.so)

I've done some searching and have tried a few remedies including reinstalling scipy and libgcc. I'm not entirely sure, but it may be an anaconda issue more than anything. I am using Ubuntu 16.04 and Python 3.6.4 :: Anaconda custom (64-bit).

**Comment by momargoh** [comment]
I've only been using pip or setup.py install to install the package, I haven't tried it with Anaconda so I'm not entirely sure either. Can you try pip in a venv and see if that works ?

**Comment by puncan** [comment]
I was able to reinstall SciPy with pip and now I can import mcycle.
