### ISSUE TITLE
References?

### ISSUE THREAD

**Issue by puncan** [momargoh/MCycle#2]
The JOSS paper markup file has no references. I see a reference placed in a bib file for CoolProp and several heat transfer correlation references under the Heat Transfer Methods documentation. The major references should be called out on the JOSS paper markup file.

**Comment by momargoh** [comment]
With the heat transfer references, they are referenced in the documentation [here](https://mcycle.readthedocs.io/library/heat_transfer_methods.html) The list of references here will keep growing as I add more, so there are no 'major references' as such, the user can select whichever is most relevant for their problem. Should I still include them?

**Comment by puncan** [comment]
I would reference the main modules like CoolProp and the papers the examples are based on.
