### ISSUE TITLE
Example problem takes too long to solve

### ISSUE THREAD

**Issue by puncan** [momargoh/MCycle#3]
The example problem hughes2017.py took about 37 minutes to solve on my laptop. Consider separating these example steps smaller executables or simplify the problem to take less time if possible.

**Comment by momargoh** [comment]
I'll create a smaller example script. It's true, that script is quite involved.

**Comment by momargoh** [comment]
@puncan The quick start example is available here https://github.com/momargoh/MCycle/tree/cython/examples/quickstart. It should run reasonably fast. The hughes2017 example that took ages has also been updated and runs in about 10mins now.
