### ISSUE TITLE
run quickstart.py has errors

### ISSUE THREAD

**Issue by shigubuhua** [momargoh/MCycle#5]
I pip MCycle 1.0.1 from git.
When i run example quickstart.py,  i got some errors, such as :
1.
mc.DEFAULTS.updateDefaults()  -> AttributeError: module 'mcycle.DEFAULTS' has no attribute 'updateDefaults'
2.
cycle.update({
    "pEvap": mc.bar2pa(10),
    "superheat": 10.,
    "TCond": mc.degC2K(25),
    "subcool": 5.
})  -> TypeError: update() takes 1 positional argument but 2 were given
3.
cycleStateKeys='all',  -> TypeError: summary() got an unexpected keyword argument 'cycleStateKeys'
4.
Q_vals = Qfraction_vals * cycle.QIn()  -> TypeError: 'float' object is not callable

and others.

I thick this example is not update for new version?

**Comment by momargoh** [comment]
The pip version is completely outdated. I have rewritten the code using Cython in an attempt to speed it up, whereas the version on pip is pure Python. Have a look at the README file, there are instructions on installing MCycle from the source code here on Github.

**Comment by shigubuhua** [comment]
I install  from github :)
>>pip search mcycle
mcycle (0.1.3)  - Power cycle sizing and analysis package
  INSTALLED: 1.0.1
  LATEST:    0.1.3

**Comment by momargoh** [comment]
Great, so just to confirm: you are able to run quickstart.py successfully now? If so I'll close this Issue. Cheers :)

**Comment by shigubuhua** [comment]
Wait a moment...
I found i used "pip install -U -e ." to install.
Now i use "py setup.py install" to try.

**Comment by shigubuhua** [comment]
After i uninstall mcycle and remove git dir, i reclone source code from github and py setup.py install.
When i run py quickstart.py, i have error:

λ py quickstart.py
Traceback (most recent call last):
  File "quickstart.py", line 3, in <module>
    import mcycle as mc
  File "D:\python\36-64\lib\site-packages\mcycle-1.0.1-py3.6-win-amd64.egg\mcycle\__init__.py", line 15, in <module>
    from . import bases
  File "D:\python\36-64\lib\site-packages\mcycle-1.0.1-py3.6-win-amd64.egg\mcycle\bases\__init__.py", line 1, in <module>
    from .mcabstractbase import MCAB
ModuleNotFoundError: No module named 'mcycle.bases.mcabstractbase'

:(

**Comment by shigubuhua** [comment]
Finally, I uninstall mcycle. And, directly import source git dir.
`import sys
try:
    sys.path.append(r"D:\git\MCycle_cpython\\")
    import mcycle as mc
except Exception as e:
    print(f"import is error: {e}")
    raise`

Then, running quickstart.py is OK.

**Comment by momargoh** [comment]
great, I'll close this issue now
