### ISSUE TITLE
Setting up MCycle issue 

### ISSUE THREAD

**Issue by guipradow** [momargoh/MCycle#6]
I have the following issue:
------------------------------------------------------------------------------------------------------------------------
>>> import mcycle as mc
>>> import CoolProp as CP

>>> mc.DEFAULTS.PLOT_DIR = "" # will not create a new folder for plots
>>> mc.DEFAULTS.PLOT_DPI = 200
>>> mc.DEFAULTS.updateDefaults()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'mcycle.DEFAULTS' has no attribute 'updateDefaults'
------------------------------------------------------------------------------------------------------------------------

Cython, numpy, scipy, matplotlib and CoolProp are all up to date

**Comment by momargoh** [comment]
Thanks for pointing this out, the name of that function has changed to checkDefaults(). I've updated that example now so it should run fine for you.

**Comment by guipradow** [comment]
Thank you very much!
I appreciate your attention.
