### ISSUE TITLE
HxSimple

### ISSUE THREAD

**Issue by Dinglebarry9** [momargoh/MCycle#8]
Thank you for creating this repo. With a little editing I was able to get the Hughes example running but for the life of me I cannot get a basic condenser heat exchanger example working. First I tried to finish the HxSimple class you were working on but was unsuccessful, so I tried a simplified HxPlate based on what you have in `heat_exchangers.py` but it either crashes the kernel or throws errors. For context I am building out an Ocean Thermal Energy rankine cycle with Ammonia as the working fluid:

`wf = mc.FlowState(
    fluid="Ammonia",
    m=1.0,
    inputPair=mc.PT_INPUTS,
    input1=913400, 
    input2=mc.degC2K(22.9)
    )`

And water as the secondary fluid for cooling:

`sf = mc.FlowState(
    fluid="Water",
    
    m=132.037,       
    inputPair=mc.PT_INPUTS,
    input1=101325,
    input2=mc.degC2K(4.2)
    )`

My set up for the HxPlate is:

`mc.HxPlate(
        flowConfig=hxFlowConfig,
        NPlate=500,
        RfWf=0,
        RfSf=0,
        plate=mc.stainlessSteel_316(),
        tPlate=0.95e-3,
        geomWf=mc.GeomHxPlateSmooth(1.45e-3),
        geomSf=mc.GeomHxPlateSmooth(1.45e-3),
        L=250e-2,
        W=111e-2,
        coeffs_LPlate=[0.060, 1],
        coeffs_WPlate=[0, 1],
        efficiencyThermal=1.0,
        flowInWf=None,
        flowInSf=None,
        flowOutWf=None,
        flowOutSf=None,
        ambient=None,
        sizeAttr="N",
    )`

Then the RankineBasic as follows:

`cycle = mc.RankineBasic(
    wf=wf, evap=evap, exp=exp, cond=cooler, comp=comp, config=config)
cycle.update({
    "pEvap": mc.bar2Pa(9.134),
    "superheat": 0.,
    "pCond": mc.bar2Pa(6.152),
    "subcool": 0.,
    'sinkIn': sf,
})`

Any ideas?

**Comment by momargoh** [comment]
Hey @Dinglebarry9 thanks for reaching out, yeah I've come to realise the examples need some major updating! So you're trying to run the cycle based on that fixed heat exchanger, using the `run` function right? That function has not been thoroughly tested because I started this package for sizing component to design condition and added the `run` function a bit last minute.

Could you explain exactly what you're trying to calculate for your cycle?

**Comment by Dinglebarry9** [comment]
Hey @momargoh thanks for getting back to me. I am not using the run function just the RankineBasic summary method. I am attempting to model an otec cycle with cooling/boiling from seawater. Then plug the outflow of the cold water HX into a secondary cycle and calculate the working fluid mass flowrate inside the second cycle. The exact geometry of the HX is not relevant right now which is why I was looking at the HxSimple class.

**Comment by momargoh** [comment]
No worries. If the geometry is not relevant at the moment try the HxPlate class or HxBasicPlanar,  you're welcome to link me to your script, I can have a quick peek, if there's no sensitive info in it.

**Comment by Dinglebarry9** [comment]
No sensitive info at all. I will tinker with it some more and see if I can get something working. Thanks for responding so quickly. I will post the setup and ping you, but for now I will close this issue, thanks.
